apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: dev
    namespace: selections
  spec:
    failedBuildsHistoryLimit: 3
    output:
      to:
        kind: ImageStreamTag
        name: dev:latest
        namespace: selections
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: https://github.com/ComputerScienceHouse/csh-selections
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.8-ubi8
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 3
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secretReference:
          name: dev-github
      type: GitHub
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: prod
    namespace: selections
  spec:
    failedBuildsHistoryLimit: 3
    output:
      to:
        kind: ImageStreamTag
        name: prod:latest
        namespace: selections
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/ComputerScienceHouse/csh-selections
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.8-ubi8
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 3
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secretReference:
          name: prod-github
      type: GitHub
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
