apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: dev
    namespace: selections
  spec:
    lookupPolicy:
      local: true
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: prod
    namespace: selections
  spec:
    lookupPolicy:
      local: true
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
