"""empty message

Revision ID: 9b43c52e2fac
Revises: 65977197d0bd
Create Date: 2025-05-06 04:20:41.966385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b43c52e2fac'
down_revision = '65977197d0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'body',
               existing_type=mysql.VARCHAR(length=6000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'body',
               existing_type=mysql.VARCHAR(length=6000),
               nullable=False)
    # ### end Alembic commands ###