"""Create Timestamps and Restrict Null Fields

Revision ID: b521b18a7cc7
Revises: a3ab8757ca1c
Create Date: 2018-04-02 18:09:59.651673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b521b18a7cc7'
down_revision = 'a3ab8757ca1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('application', 'body',
               existing_type=mysql.VARCHAR(length=6000),
               nullable=False)
    op.alter_column('application', 'gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Other'),
               nullable=False)
    op.alter_column('application', 'team',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('criteria', 'max_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('criteria', 'medium',
               existing_type=mysql.ENUM('Paper', 'Phone'),
               nullable=False)
    op.alter_column('criteria', 'min_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('criteria', 'name',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('criteria', 'weight',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('submission', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('submission', 'application',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('submission', 'medium',
               existing_type=mysql.ENUM('Paper', 'Phone'),
               nullable=False)
    op.alter_column('submission', 'member',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('submission', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('submission', 'member',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('submission', 'medium',
               existing_type=mysql.ENUM('Paper', 'Phone'),
               nullable=True)
    op.alter_column('submission', 'application',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('submission', 'created')
    op.alter_column('criteria', 'weight',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('criteria', 'name',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('criteria', 'min_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('criteria', 'medium',
               existing_type=mysql.ENUM('Paper', 'Phone'),
               nullable=True)
    op.alter_column('criteria', 'max_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('application', 'team',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('application', 'gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Other'),
               nullable=True)
    op.alter_column('application', 'body',
               existing_type=mysql.VARCHAR(length=6000),
               nullable=True)
    op.drop_column('application', 'created')
    # ### end Alembic commands ###
