"""Phone Interview Changes

Revision ID: f7fc75087f9f
Revises: b521b18a7cc7
Create Date: 2018-04-04 10:23:57.529166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fc75087f9f'
down_revision = 'b521b18a7cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('phone_int', sa.Boolean(), server_default='0', nullable=False))
    op.execute("ALTER TABLE `submission` DROP PRIMARY KEY, ADD PRIMARY KEY(`id`, `medium`);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'phone_int')
    op.execute("ALTER TABLE `submission` DROP PRIMARY KEY, ADD PRIMARY KEY(`id`);")
    # ### end Alembic commands ###
